[build]
  command = "curl -O https://dl.google.com/go/go1.19.linux-amd64.tar.gz && tar -xzf go1.19.linux-amd64.tar.gz && export PATH=$PATH:$(pwd)/go/bin && npm run build"
  publish = "build"  # Replace with your build output directory